services:
  - type: web
    name: cybix-whatsapp-bot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: SESSION_ID
        sync: false
      - key: OWNER_ID
        sync: false
      - key: BOT_NAME
        sync: false
      - key: PREFIX
        sync: false
      - key: BANNER
        sync: false
    autoDeploy: true
    healthCheckPath: /